### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by C315703603** [Lingchen218/LearningAssistance#2]
![9G0RM8RH{XIPW6J5G}}GQ~3](https://user-images.githubusercontent.com/103497700/190888602-eb8a66e5-27f0-4492-9ec4-9f14e841c10a.png)
一直显示登录中

**Comment by lingchenma** [comment]
更新一下代码再试试？

**Comment by 259029393** [comment]
一直显示正在登陆

**Comment by lingchenma** [comment]
是用代码运行的吗？在更新一下代码试试？

**Comment by lingchenma** [comment]
已经修复

**Comment by 259029393** [comment]
不知道是不是我的问题，获取课程失败







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月29日(星期四) 晚上10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lingchen218/LearningAssistance] 登录不上 (Issue #2)





 
已经修复
